[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.2", features = ["dynamic_linking"] }
bevy_simple_text_input = "0.7.0"
prost = "0.12.6"
tonic = "0.11.0"

[build-dependencies]
tonic-build = "0.11.0"
