name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Installing dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y -qq libasound2-dev libssl-dev libpulse-dev libdbus-1-dev libudev-dev curl unzip
        cd ~/ && mkdir protobuf && cd protobuf
        curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.15.8/protoc-3.15.8-linux-aarch_64.zip
        unzip protoc-3.15.8-linux-aarch_64.zip -d protoc3
        sudo mv protoc3/bin/* /usr/local/bin/
        sudo mv protoc3/include/* /usr/local/include/
        uname -m
        protoc --version
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
